### ISSUE TITLE
named logger for symphony

### ISSUE THREAD

**Issue by greenpau** [symphonyoss/python-symphony#52]
Feature request. It would be nice to be able to do things like that:

```
    logging.getLogger("requests").setLevel(logging.DEBUG)
    logging.getLogger("urllib3").setLevel(logging.DEBUG)
```

That is:

```
    logging.getLogger("symphony").setLevel(logging.DEBUG)
```

**Comment by openfly** [comment]
Makes sense.  On vacation ATM in Ireland.  Will get to it when I return.

On Jun 15, 2017 6:41 PM, "Paul Greenberg" <notifications@github.com> wrote:

Feature request. It would be nice to be able to do things like that:

    logging.getLogger("requests").setLevel(logging.DEBUG)
    logging.getLogger("urllib3").setLevel(logging.DEBUG)

That is:

    logging.getLogger("symphony").setLevel(logging.DEBUG)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/symphonyoss/python-symphony/issues/52>, or mute the
thread

**Comment by openfly** [comment]
Added in 0.2.2
